apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fintech-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
